/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tomtresansky.gitstream

class IdeLib01 {
    public boolean someLibraryMethod() {
        return true;
    }

    public int someOtherLibraryMethod() {
        return 42;
    }
    public int someOtherLibraryMethod2() {
        return 42;
    }
}
