/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tomtresansky.gitstream

// This is a JVM change without tests
class Library10 {
    public boolean someLibraryMethod() {
        return true;
    }
}
