/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tomtresansky.gitstream

// TODO: do somthing
class Library15 {
    public boolean someLibraryMethod() {
        return true;
    }

    public boolean newLibMethod() { return false; }

    private int hereIsANewMethod() { return 0; }
}
