/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tomtresansky.gitstream

class Library16NoJavadoc {
    public boolean someLibraryMethod() {
        return true;
    }
}
