/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tomtresansky.gitstream

// TODO: and a todo coamment
class Library12 {
    fun someLibraryMethod(): Boolean {
        return true
    }

    // TODO: oh noes, another todo comment
    fun newMetho(): Boolean {
        return false
    }
}
