/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tomtresansky.gitstream

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }

    fun imAnExpert() = "me"
}
