/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tomtresansky.gitstream

// TODO: do something here
class Library9 {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
