/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tomtresansky.gitstream

// TODO: uh-oh, I forgot to do this
class Library11 {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
