package com.tomtresansky.gitstream/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

class Library10Test {
    fun someLibraryMethod(): Boolean {
        return true
    }

    fun heresANewTest() = true
}
